language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: 7.0

services: PostgreSQL

before_script:
  - composer install --dev --no-interaction
  - psql -c 'create database openacalendartest;' -U postgres
  - echo "<?php" >> config.test.php
  - echo "\$CONFIG->isDebug = false;" >> config.test.php
  - echo "\$CONFIG->databaseName = 'openacalendartest';" >> config.test.php
  - echo "\$CONFIG->databaseHost = 'localhost';" >> config.test.php
  - echo "\$CONFIG->databaseUser = 'postgres';" >> config.test.php
  - echo "\$CONFIG->databasePassword = '';" >> config.test.php
  - echo "\$CONFIG->extensions = array('CuratedLists');" >> config.test.php

script: phpunit  --configuration core/tests/phpunit.xml





